name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create release zip from ./src
        run: |
          zip -r release.zip ./src/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip

      - name: Clean up
        run: rm release.zip
