name: Create Release

on:
  push:
    paths:
      - 'src/ModernDiscord16.theme.css'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from ModernDiscord16.theme.css
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=@version\s)(\d+\.\d+\.\d+)' src/ModernDiscord16.theme.css)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update ModernDiscord16.nofixes.theme.css
        run: |
          cp src/ModernDiscord16.theme.css src/ModernDiscord16.nofixes.theme.css
          sed -i '/\/\* --------------FIXES-------------- \*\//,/\/\* --------------THEME-------------- \*\//d' src/ModernDiscord16.nofixes.theme.css
          sed -i 's/with fixes for discord.*refresh//g' src/ModernDiscord16.nofixes.theme.css
          sed -i 's/ModernDiscord16 \+ fixes/ModernDiscord16/' src/ModernDiscord16.nofixes.theme.css

      - name: Create release zip from ./src (without the src folder)
        run: |
          cd src
          zip -r ../ModernDiscord16.zip .

      - name: Commit the changes to ModernDiscord16.nofixes.theme.css
        run: |
          git add src/ModernDiscord16.nofixes.theme.css
          git commit -m "Update ModernDiscord16.nofixes.theme.css to match ModernDiscord16.theme.css"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: ModernDiscord16.zip

      - name: Clean up
        run: rm ModernDiscord16.zip
