name: Create Release

on:
  push:
    paths:
      - 'src/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from ModernDiscord16.theme.css
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=@version\s)(\d+\.\d+\.\d+)' src/ModernDiscord16.theme.css)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create release zip from ./src
        run: |
          zip -r ModernDiscord16.zip ./src/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: ModernDiscord16.zip

      - name: Clean up
        run: rm ModernDiscord16.zip
